//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SafeDrivingEntities : DbContext
    {
        public SafeDrivingEntities()
            : base("name=SafeDrivingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<offers> offers { get; set; }
        public virtual DbSet<persons> persons { get; set; }
        public virtual DbSet<requests> requests { get; set; }
        public virtual DbSet<travels> travels { get; set; }
    }
}
