//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class travels
    {
        public int id { get; set; }
        public int id_offer { get; set; }
        public int id_request { get; set; }
    
        public virtual offers offers { get; set; }
        public virtual requests requests { get; set; }
    }
}
